### ISSUE TITLE
French language file?

### ISSUE THREAD

**Issue by Alexey-T** [rchastain/substitute#1]
I saw your post about PiNote editor. Can you help to update the French tranlation of CudaText, please?
https://sourceforge.net/projects/cudatext/files/addons/translations/
this dir shows that fr_FR file is from 2020/06.

wiki: https://wiki.freepascal.org/CudaText#How_to_make_translation
@rchastain

**Comment by rchastain** [comment]
OK, I will take a look ASAP.
